### ISSUE TITLE
Reusing workflows

### ISSUE THREAD

**Issue by plamentotev** [codehaus-plexus/.github#18]
GitHub actions are great automation tool but they come with some maintenance cost. Good example are some of the less active repositories like plexus-io. There are lot of commits related to upgrading GitHub actions, which are not quite useful as there are no that many commits to run those actions on. On other hand the project is not tested with Java 18 to its release, which is much more important.

Using shared workflows helps with reducing the maintenance cost. But there are multiple ways to reuse the workflows and within plexus organization there are a couple of them used. I've opened this issue in order to discuss what would be the best way to reuse workflows, as there are pros and cons to each approach.

First I think the following workflows could be reused, including their configuration: `codeql-analysis.yml`, `maven.yml` and `release-drafter.yml`.

The next question is how. In particular how to set the version used. For `codeql-analysis` and `release-drafter` it makes sense to always to use the latest version, so they could use `master`, e.g. `codehaus-plexus/.github/.github/workflows/release-drafter.yaml@master`. The GitHub actions could be upgraded only in the shared project. And then the rest will always use the latest virions form the shared project.

The Maven build is a special case. For it we can use specific version - e.g. `codehaus-plexus/.github/.github/workflows/maven.yml@v0.0.4`. This would mean there will be dependabot merge requests and commit. But in this case there is a benefit as well - if we add new the Java version in the build matrix and release new version, all repositories will receive MR with the updated version so they can be build with it. This is a kind of sem-automated way to trigger builds across the organization when there is new Java version.

What do you think?

**Comment by slachiewicz** [comment]
we should have the setup you have describd except codeql that we dont use at all.

**Comment by plamentotev** [comment]
Yes. Looks like this is not longer relevant as we reuse workflows. I'll close it.
