### ISSUE TITLE
Deploy step sometimes fails with 401

### ISSUE THREAD

**Issue by plamentotev** [codehaus-plexus/.github#44]
The deploy step failed with 401 https://github.com/codehaus-plexus/plexus-archiver/actions/runs/8996418347/job/24712968333 There were previous runs that succeeded so I suspect it is related to the user permissions of the user that made the push, but I didn't found any documentation about that on GitHub. Maybe somebody with admin access can check if the success runs are from users with different permissions?

**Comment by slawekjaranowski** [comment]
We have defined a secrets: MAVEN_DEPLOY_UID and MAVEN_DEPLOY_PWD which is used for deployment of snapshots.
There are secrets defined on organization level - only owner can update it.
As I remember @gnodet last defined it.

@gnodet - can you check / update its.

**Comment by slawekjaranowski** [comment]
@plamentotev @gnodet re-run as usual helps 😄

**Comment by plamentotev** [comment]
> @plamentotev @gnodet re-run as usual helps 😄

The interesting thing is whether the re-run was successful because the 401 issue was temporary or because you ran it. 401 (Unauthorized) error is usually returned when credentials are not present or are not valid(and in this case they are valid as the re-run shows). GitHib has some restrictions on GitHub actions that run with secrets. That is to prevent leaking the secret, otherwise it would be easy to make change in the repository and send them to a server or just print them. Most notably forks does not have access to the secrets. In their case the value of the secrets would be empty strings, which would cause 401.

Now the run is not on fork, but maybe the user and their permissions also matter. For some reason didn't found documentation on that. Or maybe it was of those misleading errors, where the real reason for the failure was not that the credentials were not correct or missing, but some internal server error (it happens even to the best 😄).

**Comment by slawekjaranowski** [comment]
@plamentotev you are right ...
The PRs from forks do not access to secrets.
All builds from repository have access - on all branches - nevermind who stary it - you can try rebuild or push direct commit

If you have a write access to repository you can introduce a code that do everything ....

**Comment by plamentotev** [comment]
> @plamentotev you are right ... The PRs from forks do not access to secrets. All builds from repository have access - on all branches - nevermind who stary it - you can try rebuild or push direct commit
> 
> If you have a write access to repository you can introduce a code that do everything ....

Thanks for the info. I re-run the last build and indeed was successful.
